-- 변수 = 필드 / 다음에 TYPE이온다 , 앞에 VAR는 가변의 의미 
-- NOT NULL : 공백 없이
-- UNIQUE : 유일하게
-- DBA : DBadmin 데이터베이스 관리자
-- () 괄호 안에 숫자 , 글자 수 , VARCHAR(50) : 최대 50이며 , 이내에서 가변 가능
-- ENUM 열거 타입 , 인덱스를 가진 표 처럼 , 문자열 숫자열 처리 가능
-- DEFAULT : 없으면 기본으로 넣어주는 , DEFAULT 'user'
-- BOOLEAN : ?
-- DB =표를 담을 공간 
